# https://docs.travis-ci.com/user/languages/julia
language: julia
os:
  - linux
julia:
  - 1.6.1
  - nightly

matrix:
  allow_failures:
    - julia: nightly
    - julia: 1.6.1
  fast_finish: true
notifications:
  email: false

after_success:
  # push coverage results to Codecov
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Codecov.submit(Codecov.process_folder())'
  # push coverage results to Coveralls
  - julia -e 'using Pkg; Pkg.add("Coverage"); using Coverage; Coveralls.submit(Coveralls.process_folder())'
